// Known-good BYO VNet + Private Endpoint + Private DNS for a Foundry hosted agent.
//
// PASTE-READY scaffold. Drop into ./infra/main.bicep alongside the resources
// generated by `azd ai agent init`, then re-run `azd up`. This file does NOT
// run `az network create` itself — that is the deploy boundary owned by azd.
//
// What this provisions:
//   1. A VNet with two subnets:
//        - agentSubnet, delegated to Microsoft.App/environments (/27)
//        - peSubnet, holds the Private Endpoints (/28)
//   2. A Private Endpoint to the Foundry account.
//   3. A Private DNS zone (privatelink.services.ai.azure.com) linked to the VNet.
//
// What this DOES NOT do (intentionally):
//   - Provision NSGs (Foundry hosted agents do not require an NSG on the delegated
//     subnet; if you add one, run deep-walk-nsg.sh to verify outbound 443).
//   - Provision Azure Firewall (only required for `allow_only_approved` outbound
//     mode with FQDN allowlisting).
//   - Provision PEs to data sources (AI Search, Storage, Cosmos) — those live
//     in the data source resource templates, not here.
//
// Tracked: TD-10 Layer 2 (deep-network).

@description('Resource group location. Foundry account must already live here.')
param location string = resourceGroup().location

@description('VNet name. Pick a name in your standard naming scheme.')
param vnetName string = 'foundry-vnet'

@description('VNet address space. DO NOT use 172.17.0.0/16 (Docker bridge collision).')
param vnetAddressPrefix string = '10.20.0.0/16'

@description('Delegated agent subnet — /27 minimum for Microsoft.App/environments.')
param agentSubnetPrefix string = '10.20.1.0/27'

@description('Private Endpoint subnet — /28 is enough for a small fan-out.')
param peSubnetPrefix string = '10.20.2.0/28'

@description('Existing Foundry account name (Microsoft.CognitiveServices/accounts kind=AIServices).')
param foundryAccountName string

resource vnet 'Microsoft.Network/virtualNetworks@2024-05-01' = {
  name: vnetName
  location: location
  properties: {
    addressSpace: {
      addressPrefixes: [vnetAddressPrefix]
    }
    subnets: [
      {
        name: 'agent-subnet'
        properties: {
          addressPrefix: agentSubnetPrefix
          delegations: [
            {
              name: 'managed-environment'
              properties: {
                serviceName: 'Microsoft.App/environments'
              }
            }
          ]
          privateEndpointNetworkPolicies: 'Disabled'
        }
      }
      {
        name: 'pe-subnet'
        properties: {
          addressPrefix: peSubnetPrefix
          privateEndpointNetworkPolicies: 'Disabled'
        }
      }
    ]
  }
}

resource foundry 'Microsoft.CognitiveServices/accounts@2025-04-01-preview' existing = {
  name: foundryAccountName
}

resource pe 'Microsoft.Network/privateEndpoints@2024-05-01' = {
  name: '${foundryAccountName}-pe'
  location: location
  properties: {
    subnet: {
      id: '${vnet.id}/subnets/pe-subnet'
    }
    privateLinkServiceConnections: [
      {
        name: '${foundryAccountName}-plsc'
        properties: {
          privateLinkServiceId: foundry.id
          // Foundry account exposes two groupIds: 'account' (control plane)
          // and 'cognitiveservices' (inference). Use 'account' for hosted agents.
          groupIds: ['account']
        }
      }
    ]
  }
}

resource dnsZone 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: 'privatelink.services.ai.azure.com'
  location: 'global'
}

resource zoneLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: dnsZone
  name: '${vnetName}-link'
  location: 'global'
  properties: {
    virtualNetwork: {
      id: vnet.id
    }
    registrationEnabled: false
  }
}

resource peDnsBinding 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2024-05-01' = {
  parent: pe
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'foundry-account'
        properties: {
          privateDnsZoneId: dnsZone.id
        }
      }
    ]
  }
}

output agentSubnetId string = '${vnet.id}/subnets/agent-subnet'
output peSubnetId string = '${vnet.id}/subnets/pe-subnet'
output privateEndpointId string = pe.id
output privateDnsZoneId string = dnsZone.id
